# Generated by Django 6.0 on 2026-01-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('instance_type', models.CharField(choices=[('t2.micro', 't2.micro (Free Tier)'), ('t3.medium', 't3.medium (General Purpose)'), ('c5.large', 'c5.large (Compute Optimized)')], default='t2.micro', max_length=20)),
                ('ami_id', models.CharField(default='ami-0c55b159cbfafe1f0', max_length=50)),
                ('environment', models.CharField(default='Dev', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.CharField(default='us-east-1', max_length=50)),
                ('security_name', models.CharField(default='web-access-sg', max_length=100)),
                ('description', models.CharField(default='Allow standard web traffic', max_length=200)),
                ('from_port', models.IntegerField(default=22)),
                ('to_port', models.IntegerField(default=22)),
                ('protocol', models.CharField(default='tcp', max_length=10)),
                ('cidr_ip', models.CharField(default='0.0.0.0/0', help_text='IP Range (e.g., 0.0.0.0/0)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('icon_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
