# Generated by Django 6.0 on 2026-01-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infrastructurerequest',
            old_name='region',
            new_name='aws_region',
        ),
        migrations.RenameField(
            model_name='infrastructurerequest',
            old_name='from_port',
            new_name='ingress_from_port',
        ),
        migrations.RenameField(
            model_name='infrastructurerequest',
            old_name='protocol',
            new_name='ingress_protocol',
        ),
        migrations.RenameField(
            model_name='infrastructurerequest',
            old_name='to_port',
            new_name='ingress_to_port',
        ),
        migrations.RenameField(
            model_name='infrastructurerequest',
            old_name='description',
            new_name='sec_group_desc',
        ),
        migrations.RenameField(
            model_name='infrastructurerequest',
            old_name='security_name',
            new_name='sec_group_name',
        ),
        migrations.RemoveField(
            model_name='infrastructurerequest',
            name='cidr_ip',
        ),
        migrations.AddField(
            model_name='infrastructurerequest',
            name='ingress_cidr',
            field=models.CharField(default='0.0.0.0/0', max_length=50),
        ),
        migrations.AddField(
            model_name='infrastructurerequest',
            name='public_key_path',
            field=models.CharField(default='/root/.ssh/web.pub', max_length=200),
        ),
        migrations.AddField(
            model_name='infrastructurerequest',
            name='user_data_script',
            field=models.TextField(default='#!/bin/bash\n', help_text='Shell script to run on startup'),
        ),
    ]
