# Generated by Django 6.0 on 2026-01-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_region_infrastructurerequest_aws_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructurerequest',
            name='aws_region',
            field=models.CharField(choices=[('us-east-1', 'US East (N. Virginia)'), ('us-east-2', 'US East (Ohio)'), ('us-west-1', 'US West (N. California)'), ('us-west-2', 'US West (Oregon)'), ('ap-south-1', 'Asia Pacific (Mumbai)'), ('ap-southeast-1', 'Asia Pacific (Singapore)'), ('eu-central-1', 'Europe (Frankfurt)'), ('eu-west-1', 'Europe (Ireland)'), ('eu-west-2', 'Europe (London)')], default='us-east-1', max_length=50),
        ),
    ]
